In [9]:
import numpy as np

arr = np.arange(1, 11)

reshaped_arr = arr.reshape(2, 5)
print(reshaped_arr)




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:

arr = np.arange(1, 21)

extracted_elements = arr[5:16]
print(extracted_elements)


[ 6  7  8  9 10 11 12 13 14 15 16]


In [4]:
import pandas as pd


fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

fruits['pears'] = 4

print(fruits)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [5]:

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack'],
    'age': [23, 30, 25, 35, 28, 40, 22, 29, 33, 31],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female', 'Male']
}

df = pd.DataFrame(data)
print(df)


      name  age  gender
0    Alice   23  Female
1      Bob   30    Male
2  Charlie   25    Male
3    David   35    Male
4      Eva   28  Female
5    Frank   40    Male
6    Grace   22  Female
7   Hannah   29  Female
8      Ivy   33  Female
9     Jack   31    Male


In [6]:
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

print(df)


      name  age  gender  occupation
0    Alice   23  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   25    Male     Analyst
3    David   35    Male  Programmer
4      Eva   28  Female     Manager
5    Frank   40    Male     Analyst
6    Grace   22  Female  Programmer
7   Hannah   29  Female     Manager
8      Ivy   33  Female     Analyst
9     Jack   31    Male  Programmer


In [7]:
age_filtered_df = df[df['age'] >= 30]
print(age_filtered_df)


    name  age  gender  occupation
1    Bob   30    Male     Manager
3  David   35    Male  Programmer
5  Frank   40    Male     Analyst
8    Ivy   33  Female     Analyst
9   Jack   31    Male  Programmer


In [11]:

df.to_csv('data.csv', index=False)
df_from_csv = pd.read_csv('data.csv')
print(df_from_csv)


      name  age  gender  occupation
0    Alice   23  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   25    Male     Analyst
3    David   35    Male  Programmer
4      Eva   28  Female     Manager
5    Frank   40    Male     Analyst
6    Grace   22  Female  Programmer
7   Hannah   29  Female     Manager
8      Ivy   33  Female     Analyst
9     Jack   31    Male  Programmer
